baseURL= "https://blog.rsinha.org/"
languageCode= "en-gb"
theme = "ananke"
title= "Ritesh's Ramblings"
canonifyurls = false
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true

[markup]
	[highlight]
		codeFences = true
		guessSyntax = false
		hl_Lines = ""
		lineNoStart = 1
		lineNos = false
		lineNumbersInTable = true
		noClasses = false
		tabWidth = 4

[languages]
	[languages.en]
		title = "Ritesh's Ramblings"
		weight = 1
		contentDir = "content"
[author]
	Handle = "rsinha"
	FirstName = "Ritesh"
	LastName = "Sinha"
[params]
	mainSections = ["posts"]
	defaultTheme = "dark"
	description = "A weird collection of posts"
	background_color_class = "bg-near-black"
	author = "rsinha"
	post_content_classes = "athelas bg-near-white"
	custom_css = ["css/custom.css", "css/syntax-monokai.css"]

[[params.ananke_socials]]
	name = "Twitter"
	link = "https://twitter.com/rsinha"
[[params.ananke_socials]]
	name = "Github"
	link = "https://github.com/ritesh"
