baseurl= "https://blog.rsinha.org/"
languageCode= "en-gb"
pygmentsstyle = "vim"
theme = "internet-weblog"
title= "blog"
Paginate = 10
SectionPagesMenu = "main"
canonifyurls = false

[author]
	Handle = "rsinha"
	FirstName = "Ritesh"
	LastName = "Sinha"
	AboutPage = "/about"
	Location = "London, UK"
	FlickrID = "55603500@N04"
[params]
	Description = "Stuff I rant about"
	ShowCopyright = true 
	RSSEnabled = true 
	RSSSections = ["Posts"] 

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[[menu.main]]
  name = "Posts"
  weight = 1
	identifier = "posts"
  url = "/posts/"

#[[menu.main]]
# name = "Snippets"
# weight = 2
#	identifier = "snippets"
# url = "/snippets/"

